import random
import pandas as pd
import datetime as dt
import smtplib

my_email = 'created email'
password = 'app password generated by you'

now = dt.datetime.now()
day = now.day
month = now.month

data = pd.read_csv('birthdays.csv')
data_dict = data.to_dict(orient='records')

for dictionary in data_dict:
    if day == dictionary['day'] and month == dictionary['month']:
        with open(f'letter_templates\\letter_{random.randint(1, 3)}.txt', 'r') as letter_template:
            letter = letter_template.read()
            letter = letter.replace('[NAME]', dictionary['name'])
            print(letter)

        # 4. Send the letter generated in step 3 to that person's email address.
        with smtplib.SMTP('smtp.gmail.com') as connection:
            connection.starttls()
            connection.login(user=my_email, password=password)
            connection.sendmail(from_addr=my_email,
                                to_addrs=f"{dictionary['email']}",
                                msg=f"subject:HAPPY BIRTHDAY!\n\nn{letter}")
